version: '3.8'

services:
  finance-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  # Saves your DB to a folder named 'data' next to this file
    environment:
      - BEARER_TOKEN= {BEARER_TOKEN}
      - SESSION_TOKEN= {SESSION_TOKEN}
